-- [nfnl] fnl/plugins/theme.fnl
local function _1_()
  local theme = require("onenord")
  local color_module = require("onenord.colors")
  local colors = color_module.load()
  theme.setup({theme = "light", styles = {comments = "NONE", strings = "NONE", keywords = "NONE", functions = "NONE", variables = "NONE", diagnostics = "underline"}, disable = {eob_lines = true, background = false, cursorline = false}, custom_highlights = {VimwikiLink = {fg = colors.dark_blue, gui = nil}, VimwikiListTodo = {fg = colors.purple}, VimwikiHeaderChar = {guibg = nil}, VimwikiError = {guibg = nil}, CursorLineNr = {bg = "#efefef"}, LineNr = {guifg = "#550055"}, Underlined = {guifg = "#15729e"}, Search = {guibg = "#f1f1f1", guifg = nil}, TreesitterContextLineNumber = {bg = "#eeeeee"}, NormalFloat = {fg = "#2E3440", bg = "#efefef"}, FloatBorder = {fg = "#efefef", bg = "#efefef"}, FloatTitle = {fg = "#6087d7"}, TelescopeNormal = {bg = "#efefef"}, TelescopeBorder = {bg = "#eeeeee", fg = "#000000"}, TelescopePromptNormal = {bg = "#cccccc"}, TelescopeResultsNormal = {bg = "#efefef"}, TelescopePreviewNormal = {bg = "#dedede"}, TelescopePromptBorder = {fg = "#000000", bg = "#cccccc"}, TelescopeResultsBorder = {fg = "#e0e0e0", bg = "#efefef"}, TelescopePreviewBorder = {fg = "#e0e0e0", bg = "#dedede"}, TelescopeResultsTitle = {bg = "#efefef", fg = colors.purple}, TelescopePromptTitle = {bg = "#cccccc", fg = colors.purple}, TelescopePreviewTitle = {bg = "#dedede", fg = colors.purple}, RenderMarkdownH1Bg = {bg = "#efefef"}, RenderMarkdownH2Bg = {bg = "#efefef"}, RenderMarkdownH3Bg = {bg = "#efefef"}, RenderMarkdownH4Bg = {bg = "#efefef"}, RenderMarkdownH5Bg = {bg = "#efefef"}, RenderMarkdownH6Bg = {bg = "#efefef"}, derMarkdownCanceled = {fg = "#59636e"}, Visual = {bg = "#fff6d5"}, CodeiumSuggestion = {fg = "#333333", bg = "#efefef"}}, custom_colors = {bg = "#ffffff"}, borders = false, fade_nc = false})
  return vim.cmd("colorscheme onenord")
end
return {"https://github.com/rmehri01/onenord.nvim", priority = 1000, dependencies = {"nvim-tree/nvim-web-devicons"}, config = _1_, lazy = false}
